let config        = require( '../common/config.js' );
let gameloop      = require( 'node-gameloop' );
let Zorbio        = require( '../common/zorbio.js' );
let Validators    = require( './Validators.js' );
let UTIL          = require( '../common/util.js' );
let Drain         = require( './Drain.js' );
let WebSocket     = require( 'ws' );
let BotController = require( './BotController.js' );
let ServerPlayer  = require( './ServerPlayer.js' );
let SessionLogger = require( './SessionLogger.js' );
let RLState       = require( '../common/RLState.js' );
let Schemas       = require( '../common/schemas.js' );
let perfNow       = require( 'performance-now' );
let uuid          = require( 'node-uuid' );
let cookie        = require( 'cookie' );
let Backend       = require( './Backend.js' );
let _             = require( 'lodash' );
let SkinCatalog   = require( '../common/SkinCatalog' );
let fs            = require( 'fs' );
let path          = require( 'path' );

/**
 * This module contains all of the app logic and state
 * @param {number} id
 * @param {Object} app
 * @param {string} server_label
 * @param {number} port
 * @constructor
 */
let AppServer = function(id, app, server_label, port) {
    //  Scope
    let self = this;

    // ID of this game instance generated by the AppProxy
    self.id = id;

    self.server_label = server_label;
    self.port         = port;
    self.uuid         = self.server_label + ':' + self.port + '-' + self.id;

    self.backend = new Backend();

    // Leaderboards
    self.leaders_1_day  = [];
    self.leaders_7_day  = [];
    self.leaders_30_day = [];

    self.app = app; // express

    // Game state
    self.model = new Zorbio.Model();
    self.model.init( config.WORLD_SIZE, config.FOOD_DENSITY );
    self.socket_uuid_map = {};  // Maps a player ID to a socket uuid
    self.clients         = {};  // Client websockets with a uuid key
    self.serverMsg       = '';

    /**
     * Status object to send to a remote data store for monitoring and analytics
     */
    self.status = {
        doctype          : 'game_instance_status',
        uuid             : self.uuid,
        clients          : 0,
        real_player_count: 0,
        players_metrics  : [],
        socket_uuid_map  : 0,
        tick_time_metric : new Zorbio.Metric( 50 ),
        au_send_metric   : new Zorbio.Metric( 100 ),
    };

    /**
     * Console.log wrapper so we can include instance id for filtering
     */
    self.log = function appLog(...args) {
        // prepend instance id to message
        args[0] = '[' + self.id + '] ' + args[0];

        console.log.apply( null, args );
    };

    self.log( 'Creating game instance with ID: ', self.id );

    /**
     * Send message to all connected clients
     * @param {Object} data
     */
    self.broadcast = function appBroadcast(data) {
        let propNames = Object.getOwnPropertyNames( self.clients );
        for (let i = 0, l = propNames.length; i < l; i++) {
            let socket_uuid = propNames[i];
            let ws          = self.clients[socket_uuid];
            if (ws.readyState === WebSocket.OPEN) {
                ws.send( data );
            }
        }
    };

    /**
     * Sends a websocket message to a specific websocket by player id
     * @param {number} player_id the id of the player ot send to
     * @param {*} msg
     */
    self.sendToPlayer = function appSendToPlayer(player_id, msg) {
        let ws = self.clients[self.socket_uuid_map[player_id]];

        if (ws && ws.readyState === WebSocket.OPEN) {
            ws.send( msg );
        }
    };

    self.addClient = function appAddClient(ws, req) {
        let headers               = JSON.stringify( req.headers );
        let NB_SRVID              = self.parseNbSrvIdCookie( req.headers.cookie );
        let socket_uuid           = uuid.v4();
        self.clients[socket_uuid] = ws;

        self.log( 'Client connection headers:', headers );
        self.log( 'Socket UUID: ', socket_uuid );

        self.sendInitGame( ws, NB_SRVID );

        // Player properties
        let currentPlayer;
        let player_id;
        let type;
        let name;
        let color;
        let skin;
        let key;

        // Pool variables for speed
        let rapidBuffer = new ArrayBuffer( 20 );
        let rapidView   = new Float32Array( rapidBuffer );

        let player_not_in_model_count = 0;

        ws.on( 'message', function wsMessage(msg) {
            if (typeof msg === 'string') {
                let message;

                try {
                    message = JSON.parse( msg );
                }
                catch (e) {
                    if (config.DEBUG) {
                        console.error( '[AppServer] error parsing json on message in wss: ', e );
                    }
                    return;  // ignore
                }

                try {
                    dispatch_json_message( message );
                }
                catch (e) {
                    // An uncaught exception here would otherwise bubble out of
                    // this event handler and crash the *entire* server process
                    // for every connected player (Node has no default recovery
                    // from an uncaught exception in an event callback) - one
                    // bad handler/message should never be able to do that.
                    console.error( '[AppServer] Caught exception handling message op', message.op, e );
                }
            }
            else if (msg.readUInt8 /* faster than instanceof Buffer */) {
                try {
                    // Read firs byte from buffer
                    let op = msg.readUInt8( 0 );
                    if (op === Schemas.ops.PLAYER_UPDATE) {
                        handle_msg_player_update( msg );
                    }
                    else if (op === Schemas.ops.LEADERBOARDS_REQUEST) {
                        handle_leaderboard_request();
                    }
                    else {
                        op = msg.readFloatLE( 0 );
                        if (op === Schemas.ops.CLIENT_POSITION_RAPID) {
                            handle_client_position_rapid( msg );
                        }
                    }
                }
                catch (e) {
                    console.error('[AppServer] Caught exception in ws.on("message") handling binary Buffer', e);
                }
            }
        } );

        /**
         * Dispatches a parsed JSON message to its handler. Split out from
         * ws.on('message') so the try/catch above covers every case here.
         * @param {Object} message
         */
        function dispatch_json_message(message) {
            switch (message.op) {
                case 'enter_game':
                    handle_enter_game( message );
                    break;
                case 'respawn':
                    handle_msg_respawn();
                    break;
                case 'player_ready':
                    handle_msg_player_ready();
                    break;
                case 'zor_ping':
                    handle_msg_zor_ping( message );
                    break;
                case 'speed_boost_start':
                    handle_msg_speed_boost_start();
                    break;
                case 'speed_boost_stop':
                    handle_msg_speed_boost_stop();
                    break;
                case 'admin_set_bots_enabled':
                    handle_msg_admin_set_bots_enabled( message );
                    break;
                case 'admin_set_rl_enabled':
                    handle_msg_admin_set_rl_enabled( message );
                    break;
                case 'admin_set_paused':
                    handle_msg_admin_set_paused( message );
                    break;
                case 'admin_set_max_bots':
                    handle_msg_admin_set_max_bots( message );
                    break;
                case 'admin_set_rl_threshold':
                    handle_msg_admin_set_rl_threshold( message );
                    break;
                case 'admin_debug_stats_request':
                    handle_msg_admin_debug_stats_request();
                    break;
                case 'admin_reset_bots':
                    handle_msg_admin_reset_bots();
                    break;
                case 'admin_apply_world_settings':
                    handle_msg_admin_apply_world_settings( message );
                    break;
                case 'admin_set_bot_max_spawn_scale':
                    handle_msg_admin_set_bot_max_spawn_scale( message );
                    break;
                case 'switch_player_type':
                    handle_msg_switch_player_type( message );
                    break;
                case 'admin_set_bots_can_eat_bots':
                    handle_msg_admin_set_bots_can_eat_bots( message );
                    break;
            }
        }

        ws.on( 'close', function wsClose() {
            handle_close();
        } );

        ws.on( 'error', function(e) {
            console.error( 'WebSocket error occured for player_id', player_id, e );
        } );

        /**
         * Handle enter game message from the client this is the first message sent from
         * a player who is connecting to the server
         * @param {Object} msg
         */
        function handle_enter_game(msg) {
            player_id = Zorbio.IdGenerator.get_next_id();
            // whitelist the client-supplied type - only PLAYER or SPECTATOR are valid to self-select
            type      = msg.type === Zorbio.PlayerTypes.SPECTATOR ? Zorbio.PlayerTypes.SPECTATOR : Zorbio.PlayerTypes.PLAYER;
            name      = msg.name;
            color     = msg.color;
            skin      = SkinCatalog[msg.skin] ? msg.skin : 'default';  // validate skin name
            key       = msg.key;

            // Sanitize player name
            name = UTIL.filterName( name );

            self.log( 'Player enter request: ', player_id, type, name, color, skin, key );

            // spawn the player
            handle_msg_respawn();
        }

        /**
         * Handle the respawn message from the client. This prepares the player object on the server
         * but doesn't add them to the game until the player ready message is received.
         */
        function handle_msg_respawn() {
            let position = self.model.getSafeSpawnPosition( 10 );

            if (currentPlayer && self.isPlayerInGame( currentPlayer.id )) {
                // make sure this player isn't already connected and playing
                self.log( 'Respawn error: Player is already in game' );
                self.kickPlayer( currentPlayer.id, 'Forced respawn.' );
                return;
            }

            // Create the Player
            currentPlayer             = new ServerPlayer( player_id, name, color, skin, type, position, ws );
            currentPlayer.headers     = headers;
            currentPlayer.socket_uuid = socket_uuid;
            currentPlayer.isAdmin     = config.ADMIN_NAMES.indexOf( name.toLowerCase() ) !== -1;

            // See if this is PAUL LYONS
            if (name === 'PAUL LYONS' && skin === 'lyons') {
                self.log('PAUL LYONS GOD MODE!');
                const bigScale = 70;
                currentPlayer.sphere.scale = bigScale;
                currentPlayer.sphere.expectedScale = bigScale;
            }

            // Send welcome message
            let msg    = {
                0     : Schemas.ops.WELCOME,
                player: currentPlayer.reduce(),
            };
            let buffer = Schemas.welcomeSchema.encode( msg );
            ws.send( buffer );

            if (currentPlayer.isAdmin) {
                send_admin_status();
            }

            self.log( 'User ' + currentPlayer.id + ' spawning into the game' );
        }

        /**
         * Sends the current admin-controllable bot state to this socket. Only meaningful
         * for admin players - the client only shows the admin panel when is_admin is true.
         */
        function send_admin_status() {
            ws.send( JSON.stringify( {
                op            : 'admin_status',
                is_admin      : true,
                bots_enabled  : self.botController.enabled,
                rl_enabled    : self.botController.rlEnabled,
                paused        : self.paused,
                max_bots      : config.MAX_BOTS,
                rl_threshold  : config.RL_BOT_SIZE_THRESHOLD,
                bot_max_spawn_scale: config.BOT_MAX_SPAWN_SCALE,
                bots_can_eat_bots: config.BOTS_CAN_EAT_BOTS,
                world_size    : config.WORLD_SIZE,
                food_density  : config.FOOD_DENSITY,
            } ) );
        }

        /**
         * Sends a snapshot of every player/bot's food and player capture
         * counts, for the admin debug panel. Not part of the regular actor
         * broadcast (which is a fixed binary schema) - this is a plain JSON
         * message sent only on request, only to admins.
         */
        function send_admin_debug_stats() {
            let stats = self.model.players.map( function( p ) {
                return {
                    id            : p.id,
                    name          : p.name,
                    type          : p.type,
                    scale         : Math.round( p.sphere.scale ),
                    foodCaptures  : p.foodCaptures,
                    playerCaptures: p.playerCaptures,
                };
            } );

            ws.send( JSON.stringify( { op: 'admin_debug_stats', stats: stats } ) );
        }

        /**
         * Handles an admin toggling bots on/off. Ignored for non-admin players.
         * @param {Object} msg
         */
        function handle_msg_admin_set_bots_enabled(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            self.botController.setEnabled( !!msg.value );
            self.log( 'Admin', currentPlayer.id, 'set bots enabled:', self.botController.enabled );
            send_admin_status();
        }

        /**
         * Handles an admin toggling the RL movement pattern for large bots. Ignored for
         * non-admin players.
         * @param {Object} msg
         */
        function handle_msg_admin_set_rl_enabled(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            self.botController.setRlEnabled( !!msg.value );
            self.log( 'Admin', currentPlayer.id, 'set RL bots enabled:', self.botController.rlEnabled );
            send_admin_status();
        }

        /**
         * Handles an admin toggling whether bots can capture (eat) each
         * other, not just humans. Off by default - population turns over
         * fast once bots start eating bots, but replenishBot() already
         * backfills losses (see captureBot), so it's self-stabilizing.
         * @param {Object} msg
         */
        function handle_msg_admin_set_bots_can_eat_bots(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            config.BOTS_CAN_EAT_BOTS = !!msg.value;
            self.log( 'Admin', currentPlayer.id, 'set bots can eat bots:', config.BOTS_CAN_EAT_BOTS );
            send_admin_status();
        }

        /**
         * Handles an admin opening/closing the mod menu - freezes bot movement
         * and player/bot captures while open so parameters can be adjusted
         * without the world (or the admin) changing under them. This is a
         * server-wide pause, not per-player - on a private dev server with a
         * single admin that's an acceptable tradeoff, but it will also freeze
         * any other connected player's game.
         * @param {Object} msg
         */
        function handle_msg_admin_set_paused(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            self.paused = !!msg.value;
            self.log( 'Admin', currentPlayer.id, 'set paused:', self.paused );
            send_admin_status();
        }

        /**
         * Handles an admin adjusting the desired bot population live. Spawns
         * or despawns immediately to match, rather than waiting for the next
         * capture/disconnect to notice the new value.
         * @param {Object} msg
         */
        function handle_msg_admin_set_max_bots(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            let value = Math.max( 0, Math.min( 50, parseInt( msg.value, 10 ) || 0 ) );
            self.applyMaxBots( value );
            self.log( 'Admin', currentPlayer.id, 'set max bots:', config.MAX_BOTS );
            send_admin_status();
        }

        /**
         * Handles an admin adjusting the size threshold above which bots use
         * the 'hunt'/'rl' pattern instead of a random curve. Only affects
         * bots spawned after the change.
         * @param {Object} msg
         */
        function handle_msg_admin_set_rl_threshold(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            let value = Math.max( 1, Math.min( 200, parseInt( msg.value, 10 ) || config.RL_BOT_SIZE_THRESHOLD ) );
            config.RL_BOT_SIZE_THRESHOLD = value;
            self.log( 'Admin', currentPlayer.id, 'set RL bot size threshold:', value );
            send_admin_status();
        }

        /**
         * Handles an admin adjusting the cap on newly-spawned bot size. The
         * spawn curve always makes the first bot after a reset the biggest -
         * lowering this flattens that "one guaranteed giant bot" pattern.
         * Only affects bots spawned after the change.
         * @param {Object} msg
         */
        function handle_msg_admin_set_bot_max_spawn_scale(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            let value = Math.max( 10, Math.min( 150, parseInt( msg.value, 10 ) || config.BOT_MAX_SPAWN_SCALE ) );
            config.BOT_MAX_SPAWN_SCALE = value;
            self.log( 'Admin', currentPlayer.id, 'set bot max spawn scale:', value );
            send_admin_status();
        }

        /**
         * Switches the current connection between PLAYER and SPECTATOR
         * without a disconnect/rejoin. Available to anyone, not just admins -
         * spectating already is. Becoming a SPECTATOR keeps position as-is;
         * becoming a PLAYER always respawns small at a fresh safe position -
         * resuming at whatever size/location the spectator had would let
         * someone dodge into spectator mode when threatened and pop back
         * safe, which defeats the point of it being a non-competitive mode.
         * @param {Object} msg
         */
        function handle_msg_switch_player_type(msg) {
            if (!currentPlayer) return;

            let newType = msg.value === Zorbio.PlayerTypes.SPECTATOR
                ? Zorbio.PlayerTypes.SPECTATOR : Zorbio.PlayerTypes.PLAYER;

            if (newType === currentPlayer.type) return;

            if (newType === Zorbio.PlayerTypes.PLAYER) {
                let position = self.model.getSafeSpawnPosition( 10 );
                currentPlayer.sphere.position.copy( position );
                // sphere.velocity is a plain {x,y,z} object, not a THREE.Vector3
                // (ServerPlayer never passes one at construction) - no .set() method
                currentPlayer.sphere.velocity.x = 0;
                currentPlayer.sphere.velocity.y = 0;
                currentPlayer.sphere.velocity.z = 0;
                currentPlayer.sphere.recentPositions = [];
                currentPlayer.sphere.scale = config.INITIAL_PLAYER_RADIUS;
                currentPlayer.sphere.expectedScale = config.INITIAL_PLAYER_RADIUS;
                currentPlayer.score = currentPlayer.sphere.scale;
                currentPlayer.foodCaptures = 0;
                currentPlayer.playerCaptures = 0;
            }

            currentPlayer.type = newType;
            type = newType; // keep this connection's closure-local `type` in sync for later handlers

            self.log( 'Player', currentPlayer.id, 'switched type to', newType );

            // tell every client (including this one) to rebuild this
            // player's view - a live type change invalidates assumptions
            // (visibility, movement rules) baked in when the view was built
            self.broadcast( JSON.stringify( {
                op      : 'player_type_changed',
                playerId: currentPlayer.id,
                type    : newType,
                position: currentPlayer.sphere.position,
                scale   : currentPlayer.sphere.scale,
            } ) );
        }

        function handle_msg_admin_debug_stats_request() {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            send_admin_debug_stats();
        }

        /**
         * Clears and respawns every bot at the current world settings - no
         * restart needed, since this doesn't touch food/world size, just the
         * live bot list. Useful for clearing out bots that grew oversized
         * during testing without wanting a full environment reset.
         */
        function handle_msg_admin_reset_bots() {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            self.resetAllBots();
            self.log( 'Admin', currentPlayer.id, 'reset all bots' );
            send_admin_debug_stats();
        }

        /**
         * Applies a new world size / food density by writing them into
         * common/config.js on disk and letting supervisor's file-watch
         * restart the server process - the process itself isn't killed by
         * this code, just the file is edited. Every connected client
         * (including this one) will see its socket close a moment later and
         * auto-reload (see z_handleNetworkTermination) to rejoin the fresh
         * environment. This can't be done live: the food buffer size and
         * world bounds are baked into every connected client's scene at
         * join time, so a live resize would desync anyone already connected.
         * @param {Object} msg
         */
        function handle_msg_admin_apply_world_settings(msg) {
            if (!currentPlayer || !currentPlayer.isAdmin) return;

            let worldSize   = Math.max( 500, Math.min( 3000, parseInt( msg.world_size, 10 ) || config.WORLD_SIZE ) );
            let foodDensity = Math.max( 5, Math.min( 45, parseInt( msg.food_density, 10 ) || config.FOOD_DENSITY ) );

            self.log( 'Admin', currentPlayer.id, 'applying world_size:', worldSize,
                'food_density:', foodDensity, '- this will restart the server' );

            let configPath = path.join( __dirname, '..', 'common', 'config.js' );
            let src         = fs.readFileSync( configPath, 'utf8' );

            src = src.replace( /(config\.WORLD_SIZE\s*=\s*)\d+(;)/, '$1' + worldSize + '$2' );
            src = src.replace( /(config\.FOOD_DENSITY\s*=\s*)\d+(;)/, '$1' + foodDensity + '$2' );

            fs.writeFileSync( configPath, src );
        }

        /**
         * Handles the player ready message. The client is ready to go so lets add the player
         * to the game state and the list of players. Replace any bots if needed.
         */
        function handle_msg_player_ready() {
            self.log( 'Player ' + currentPlayer.id + ' client ready' );

            // Save mapping of player_id to socket uuid
            self.socket_uuid_map[currentPlayer.id] = socket_uuid;

            // Set initial times
            currentPlayer.lastHeartbeat = Date.now();
            currentPlayer.spawnTime     = Date.now();

            // Pass any data to the for final setup
            ws.send( JSON.stringify( { op: 'game_setup' } ) );

            // give the client player time to load the game before notifying other players to add them
            setTimeout( function playerJoinDelay() {
                // Notify other clients that player has joined
                self.broadcast( JSON.stringify( { op: 'player_join', player: currentPlayer } ) );

                // Add the player to the model
                self.model.addPlayer( currentPlayer, true );

                let playerCount = self.model.players.length;
                self.log( 'Player ' + currentPlayer.id + ' joined game!' );
                self.log( 'Total real players: ' + self.model.getRealPlayers().length );

                // see if we need to remove a bot - spectators don't take a slot, so they
                // never bump a bot out to make room
                if (currentPlayer.type !== Zorbio.PlayerTypes.SPECTATOR &&
                    self.botController.hasBots() && playerCount > config.MAX_BOTS) {
                    let bot = self.botController.popBot();

                    // notify other players that this bot was removed
                    self.broadcast( JSON.stringify( { op: 'remove_player', playerId: bot.player.id } ) );
                }
            }, 200 );
        }

        /**
         * Handle the ping message from the client. respond with pong and and records the
         * clients ping latency to metrics.
         * @param {Object} msg
         */
        function handle_msg_zor_ping(msg) {
            currentPlayer.lastHeartbeat = Date.now();

            // save recent pings and fps
            if (msg.lastPing >= 0) {
                currentPlayer.ping_metric.add( msg.lastPing );
            }

            currentPlayer.fps_metric.add( msg.fps );

            ws.send( JSON.stringify( { op: 'zor_pong' } ) );
        }

        /**
         * Handle the client position rapid update. A small binary message from players
         * that is sent every frame (60Hz) with their ID and current position.
         * @param {object} buffer
         */
        function handle_client_position_rapid(buffer) {
            if (!config.ENABLE_RAPID_UPDATES) return;

            let viewIndex = 0;
            for (let bufferIndex = 0, l = buffer.length; bufferIndex < l; bufferIndex += 4) {
                rapidView[viewIndex] = buffer.readFloatLE( bufferIndex );
                viewIndex++;
            }

            let actor = self.model.getActorById( rapidView[1] );
            if (actor) {
                actor.position.set( rapidView[2], rapidView[3], rapidView[4] );
                // TODO: figure out something better that's scalable
                // self.broadcast(rapidBuffer);
            }
        }

        /**
         * Handle request for leaderboards data. Respond with recent leaderboards info.
         */
        function handle_leaderboard_request() {
            self.sendLeaderboardsUpdate( ws );
        }

        /**
         * Handle regular player update message. This is sent every 50ms from the client,
         * and contains their ID, position, food they've queued to eat, and recent positions.
         * @param {object} buffer
         */
        function handle_msg_player_update(buffer) {
            if (!currentPlayer) return;

            currentPlayer.lastHeartbeat = Date.now();

            // record timing
            let nowTime                               = Date.now();
            let receive_gap                           = nowTime - currentPlayer.pp_receive_metric.last_time;
            currentPlayer.pp_receive_metric.last_time = nowTime;

            // Decode the buffer
            let msg = Schemas.playerUdateSchema.decode( buffer );

            // Save the client metrics
            currentPlayer.pp_send_metric.add( msg.pp_gap );
            currentPlayer.pp_receive_metric.add( receive_gap );
            currentPlayer.au_receive_metric.add( msg.au_gap );
            currentPlayer.buffered_amount_metric.add( msg.buffered_mount );

            // Build the validation object
            let latestPosition = msg.latest_position;
            let sphere         = {
                id            : msg.sphere_id,
                oldestPosition: msg.oldest_position,
                latestPosition: latestPosition,
                scale         : latestPosition.radius,
            };

            // Fixes bug #145 the client may send one last position update before they are removed from the game
            let err;
            let actor = self.model.getActorById( sphere.id );
            if (!actor) {
                err = Validators.ErrorCodes.PLAYER_NOT_IN_MODEL;
            }
            else {
                err = Validators.movementSampled( sphere, actor, self.model );
            }

            if (!err) {
                // update the players position in the model
                actor.position.set( latestPosition.position.x, latestPosition.position.y, latestPosition.position.z );

                // Recent positions
                actor.pushRecentPosition( msg.prev_position_3 );
                actor.pushRecentPosition( msg.prev_position_2 );
                actor.pushRecentPosition( msg.prev_position_1 );
                actor.pushRecentPosition( latestPosition );

                // Iterate over pending food captures
                msg.food_capture_queue.forEach( function captureEachFood(food_entry) {
                    self.foodCapture( currentPlayer, food_entry.fi, actor, food_entry.radius );
                } );
            }
            else {
                switch (err) {
                    case Validators.ErrorCodes.SPEED_TO_FAST: {
                        ws.send( JSON.stringify( { op: 'speeding_warning' } ) );
                        let playerObj = self.model.getPlayerById( currentPlayer.id );
                        if (playerObj) {
                            playerObj.infractions_speed.push(config.INFRACTION_SPEED_EXPIRE);
                        }
                        break;
                    }
                    case Validators.ErrorCodes.PLAYER_NOT_IN_MODEL:
                        player_not_in_model_count++;
                        if (player_not_in_model_count > config.MAX_NOT_IN_MODEL_ERRORS) {
                            self.log( 'Player had to many not-in-model errors', player_not_in_model_count );
                            self.kickPlayer( currentPlayer.id, 'Disconnected from server' );
                            // self.removePlayerSocket(socket_uuid);
                        }
                        self.log( "Recieved 'player_update' from player not in model!", sphere.id );
                        break;
                }
            }
        }

        /**
         * Handle client closed connection
         */
        function handle_close() {
            self.removePlayerSocket( socket_uuid );

            // Safety net: if the admin who paused the world (opened the mod
            // menu) disconnects before their client manages to send the
            // unpause - e.g. leaveGameGracefully() closes the socket before
            // the resulting state change tries to send it, or a crash/tab
            // close skips that entirely - the world would otherwise stay
            // frozen forever, since nothing else ever clears self.paused.
            if (currentPlayer && currentPlayer.isAdmin && self.paused) {
                self.paused = false;
                self.log( 'Admin', player_id, 'disconnected while paused - auto-unpausing' );
            }

            if (player_id) {
                self.log( 'Player connection closed for player_id:', player_id );

                // Save their score to leaderboard if they were in game and got any points
                if (currentPlayer && self.model.getPlayerById( player_id )) {
                    self.savePlayerScore( currentPlayer.name, currentPlayer.getScore() );
                }

                // notify other clients to remove this player
                self.broadcast( JSON.stringify( { op: 'remove_player', playerId: player_id } ) );

                self.removePlayerFromModel( player_id );

                // remove the map of the player id to the socket uuid
                if (self.socket_uuid_map[player_id]) {
                    delete self.socket_uuid_map[player_id];
                }

                self.replenishBot();
            }
            else {
                self.log( 'Menu socket connection closed: ', headers );
            }
        }

        /**
         * Handle speed boost request form client.  Respond if valid or not.
         */
        function handle_msg_speed_boost_start() {
            if (currentPlayer.abilities.speed_boost.activate( currentPlayer )) {
                // Tell client to activate speed boost
                ws.send( JSON.stringify( { op: 'speed_boost_res', is_valid: true } ) );
            }
        }

        /**
         * Handle speed boost stop message. Deactivate ability on player.
         */
        function handle_msg_speed_boost_stop() {
            currentPlayer.abilities.speed_boost.deactivate();
        }
    };

    /**
     * Safe method to parse Linode NB_SRVID cookie if it exists.  the NB_SRVID is the id of the nodebalancer node
     * this client will be routed too.
     * @param {string} cookie_header
     * @returns {string}
     */
    self.parseNbSrvIdCookie = function appParseNbSrvIdCookie(cookie_header) {
        let nb_srv_id = '';  // default to empty string

        if (!cookie_header) return nb_srv_id;

        try {
            let cookies = cookie.parse( cookie_header );
            // noinspection JSUnresolvedVariable
            nb_srv_id   = cookies.NB_SRVID ? cookies.NB_SRVID : '';
        }
        catch (e) {
            return nb_srv_id;
        }

        return nb_srv_id;
    };

    self.updateActorDrains = function appUpdateActorDrains(drainers) {
        // update drains
        let drainer;
        let drainee;
        let drain_target;
        let drainee_id;
        let player_id;
        let player;
        let drain_amount;

        let i = self.model.players.length;

        // iterate over players and set their drain targets
        while (i--) {
            player                  = self.model.players[i];
            player_id               = player.id;
            drainer                 = player.sphere;
            drainer.drain_target_id = 0;  // reset

            drain_target = drainers[player_id][0];

            if (drain_target && drain_target.id > 0) {
                drainee_id = drain_target.id;

                drainer.drain_target_id = drainee_id;
                let drainee_player      = self.model.getPlayerById( drainee_id );
                drainee                 = drainee_player.sphere;

                if (config.BOTS_CAN_DRAIN_BOTS
                    || player.type !== Zorbio.PlayerTypes.BOT || drainee_player.type !== Zorbio.PlayerTypes.BOT) {
                    drain_amount = Drain.amount( drain_target.dist )
                        * Drain.bonusAmount( drainer.scale, drainee.scale );

                    // Grow the drainer and add to their score
                    player.score += drainer.growExpected( +drain_amount );

                    drainee.growExpected( -drain_amount );

                    player.drainAmount += +drain_amount;  // save drain amount stat

                    // if the drain caused the drainer to get bigger than the drainee,
                    // correct so that they're the same size.  drain shouldn't be able
                    // to make a player larger than another because it leads to
                    // infinite back and forth draining.
                    if (drainer.scale > drainee.scale) {
                        drainer.scale = drainee.scale = ( drainer.scale + drainee.scale ) / 2;
                    }
                }
            }
        }
    };

    self.playerUpdates = function appPlayerUpdates() {
        // call update() on all the player model objects
        self.model.players.forEach( function updateEachPlayer(player) {
            player.update();
        } );
    };

    self.sendInitGame = function appSendInitGame(ws, NB_SRVID) {
        let initialModel    = self.model.reduce();
        let initGameMessage = {
            0       : Schemas.ops.INIT_GAME,
            NB_SRVID: NB_SRVID,
            model   : initialModel,
        };
        let buffer          = Schemas.initGameSchema.encode( initGameMessage );
        ws.send( buffer );
    };

    self.sendLeaderboardsUpdate = function appSendLeaderboardsUpdate(ws) {
        let responseMsg = {
            0             : Schemas.ops.LEADERBOARDS_UPDATE,
            leaders_1_day : self.leaders_1_day,
            leaders_7_day : self.leaders_7_day,
            leaders_30_day: self.leaders_30_day,
        };

        let responseBuffer = Schemas.leaderboardUpdateSchema.encode( responseMsg );

        console.log( 'Sending leaderboards update' );

        ws.send( responseBuffer );
    };

    self.sendActorUpdates = function appSendActorUpdates() {
        let tinyActors          = self.model.reduceActors( true );
        let actorUpdatesMessage = { 0: Schemas.ops.ACTOR_UPDATES, actors: tinyActors };
        let buffer              = Schemas.actorUpdatesSchema.encode( actorUpdatesMessage );
        self.broadcast( buffer );

        // record timing
        let nowTime                          = Date.now();
        let send_gap                         = nowTime - self.status.au_send_metric.last_time;
        self.status.au_send_metric.last_time = nowTime;
        self.status.au_send_metric.add( send_gap );
    };

    self.foodCapture = function appFoodCapture(player, fi, actor, origRadius) {
        let food_value = config.FOOD_GET_VALUE( origRadius );

        let err = Validators.foodCapture( self.model, fi, actor, origRadius );

        if (!err) {
            self.model.food_respawning[fi] = config.FOOD_RESPAWN_TIME;

            // Increment the players food captures
            player.foodCaptures++;

            // grow player and add to their score
            player.score += player.sphere.growExpected( food_value );

            // Queue to notify clients of food capture so they can update their food view
            self.model.food_captured_queue.push( fi );
        }
        else {
            switch (err) {
                case Validators.ErrorCodes.FOOD_CAPTURE_TO_FAR:
                    // inform client of invalid capture, and make them shrink, mark infraction
                    self.model.getPlayerById( player.id ).infractions_food++;
                    break;
                case Validators.ErrorCodes.PLAYER_NOT_IN_MODEL:
                    self.log( "Recieved 'foodCapture' from player not in model!", actor.id );
                    break;
            }
        }
    };

    /**
     * Checks all players for captures
     */
    self.updatePlayerCaptures = function appUpdatePlayerCaptures() {
        let players_array = self.model.players;
        let p1;
        let p2;
        let distance;

        let j = 0;
        let i = players_array.length;

        while (i--) {
            j = i + 1;

            p1 = players_array[i];

            while (j--) {
                if (i === j) continue; // don't compare player to itself

                // find the distance between these two players
                p2 = players_array[j];

                // See if these players are close enough for capture checking
                distance = p1.sphere.position.distanceTo( p2.sphere.position );

                // players to far apart for capture checking
                if (distance > p1.getCaptureRange() && distance > p2.getCaptureRange()) continue;

                // Check if player capture should happen between these two players
                let result = self.checkPlayerCapture( p1, p2 );
                if (result) {
                    self.capturePlayer( result.attackingPlayerId, result.targetPlayerId );

                    // p1 got captured so move to the next player
                    if (result.targetPlayerId === p1.id) {
                        break;
                    }
                }
            }
        }
    };

    /**
     * Compares two players to see if a capture should occur
     * @param {Object} p1
     * @param {Object} p2
     * @returns {*} returns folse if no capture, other wise the ids of attacking and target players
     */
    self.checkPlayerCapture = function appCheckPlayerCapture(p1, p2) {
        // Spectators are pure observers - they can neither capture nor be captured
        if (p1.type === Zorbio.PlayerTypes.SPECTATOR || p2.type === Zorbio.PlayerTypes.SPECTATOR) return false;

        let p1_scale;
        let p2_scale;
        let distance;
        let p1_rp = p1.sphere.recentPositions;
        let p2_rp = p2.sphere.recentPositions;

        if (p1_rp.length < 4 || p2_rp.length < 4) return; // give brand new players time to load positions

        for (let i = p1_rp.length - 4; i < p1_rp.length; i++) {
            for (let j = p2_rp.length - 4; j < p2_rp.length; j++) {
                let rp1 = p1_rp[i];
                let rp2 = p2_rp[j];

                distance = rp1.position.distanceTo( rp2.position );

                p1_scale = rp1.radius;
                p2_scale = rp2.radius;

                // if distance is less than radius of p1 and p1 larger than p2, p1 captures p2
                // if distance is less than radius of p2 and p2 larger than p1, p2 captures p1

                if (distance < (p1_scale + config.PLAYER_CAPTURE_EXTRA_TOLERANCE) && p1_scale > p2_scale) {
                    return { attackingPlayerId: p1.id, targetPlayerId: p2.id };
                }
                else if (distance < (p2_scale + config.PLAYER_CAPTURE_EXTRA_TOLERANCE) && p2_scale > p1_scale) {
                    return { attackingPlayerId: p2.id, targetPlayerId: p1.id };
                }
            }
        }

        return false;
    };

    self.capturePlayer = function appCapturePlayer(attackingPlayerId, targetPlayerId) {
        let attackingPlayer = self.model.getPlayerById( attackingPlayerId );
        let targetPlayer    = self.model.getPlayerById( targetPlayerId );

        if (!attackingPlayer || !targetPlayer) {
            self.log( 'ERROR: player capture attacking or target player undefined.' );
            return;
        }

        if (!config.BOTS_CAN_EAT_BOTS
            && attackingPlayer.type === Zorbio.PlayerTypes.BOT && targetPlayer.type === Zorbio.PlayerTypes.BOT) {
            // Bots don't capture each other by default - admin-adjustable live
            return;
        }

        self.log( 'Capture player: ', attackingPlayerId, targetPlayerId );

        // Increment player captures for the attacking player
        attackingPlayer.playerCaptures++;

        // grow the attacking player the expected amount
        let attackingSphere = attackingPlayer.sphere;
        let targetSphere    = targetPlayer.sphere;
        let amount          = config.PLAYER_CAPTURE_VALUE( targetSphere.radius() );

        // Grow the capturing player and add to their score
        attackingPlayer.score += attackingSphere.growExpected( amount );

        if (attackingPlayer.type !== Zorbio.PlayerTypes.BOT) {
            // Inform the attacking player that they captured target player
            self.sendToPlayer( attackingPlayerId, JSON.stringify( {
                op            : 'captured_player',
                targetPlayerId: targetPlayerId,
            } ) );
        }

        if (targetPlayer.type !== Zorbio.PlayerTypes.BOT) {
            // Inform the target player that they died
            let time_alive   = Math.floor( (Date.now() - targetPlayer.spawnTime) / 1000 );
            let score        = targetPlayer.getScore();
            let size         = config.GET_PADDED_INT( targetSphere.scale );
            let drain_amount = config.GET_PADDED_INT( targetPlayer.drainAmount );

            const msgObj = {
                0                  : Schemas.ops.YOU_DIED,
                attacking_player_id: attackingPlayerId,
                food_captures      : targetPlayer.foodCaptures,
                player_captures    : targetPlayer.playerCaptures,
                drain_ammount      : drain_amount,
                time_alive         : time_alive,
                score              : score,
                size               : size,
            };

            let buffer = Schemas.youDied.encode( msgObj );

            // Notify the target player that they died
            self.sendToPlayer( targetPlayerId, buffer );

            // Save score to leaderboard if they got any points
            self.savePlayerScore( targetPlayer.name, score, self.clients[self.socket_uuid_map[targetPlayerId]] );

            // Tag this death in the training log so bad play (e.g. getting
            // caught by another player) can be excluded from behavioral cloning
            self.sessionLogger.logDeath( targetPlayer, attackingPlayer );
        }
        else {
            self.captureBot(targetPlayerId);
        }

        self.removePlayerFromModel( targetPlayerId );

        // Inform the bot controller to in case the captured player was a chase target
        self.botController.validateChaseTargets();

        // Inform other clients that target player died
        const msgObj = { op: 'player_died', attackingPlayerId: attackingPlayerId, targetPlayerId: targetPlayerId };
        self.broadcast( JSON.stringify( msgObj ) );
    };

    /**
     * Captures a bot and removes it from the game, and adds another if needed
     * @param {number} botId
     */
    self.captureBot = function appCaptureBot(botId) {
        self.botController.removeBot(botId);
        self.replenishBot();
    };

    self.isPlayerInGame = function appIsPlayerInGame(player_id) {
        return (self.model.getPlayerById( player_id ) && self.clients[self.socket_uuid_map[player_id]]);
    };

    self.kickPlayer = function appKickPlayer(playerId, reason) {
        self.log( 'kicking player: ', playerId, reason );

        // notify player that they are kicked
        self.sendToPlayer( playerId, JSON.stringify( { op: 'kick', reason: reason } ) );

        // notify other clients
        self.broadcast( JSON.stringify( { op: 'remove_player', playerId: playerId } ) );

        self.removePlayerFromModel( playerId );
    };

    self.removePlayerFromModel = function appRemovePlayerFromModel(playerId) {
        self.model.removePlayer( playerId );
        self.log( 'Removed player:', playerId );
    };

    self.removePlayerSocket = function appRemovePlayerSocket(uuid) {
        if (self.clients[uuid]) {
            if (self.clients[uuid].readyState === WebSocket.OPEN) {
                self.clients[uuid].close();
            }
            delete self.clients[uuid];
            self.log( 'Deleted client socket: ', uuid );
        }
    };

    self.checkHeartbeats = function appCheckHeartbeats() {
        if (!config.HEARTBEAT_ENABLE) return;

        let time = Date.now();

        self.model.players.forEach( function checkPlayerHeartbeats(player) {
            if (player && player.type !== Zorbio.PlayerTypes.BOT && player.lastHeartbeat) {
                if ((time - player.lastHeartbeat) > config.HEARTBEAT_TIMEOUT) {
                    let msg = 'You were kicked because last heartbeat was over ' + (config.HEARTBEAT_TIMEOUT / 1000) + ' seconds ago.';
                    self.kickPlayer( player.id, msg );
                }
            }
        } );
    };

    self.updateFoodRespawns = function appUpdateFoodRespawns() {
        // keep a current reference of which food indexes are respawning
        self.model.food_respawning_indexes = [];

        for (let i = 0, l = self.model.food_respawning.length; i < l; ++i) {
            if (self.model.food_respawning[i] > 0) {
                let timeLeft                  = self.model.food_respawning[i] - config.TICK_SLOW_INTERVAL;
                self.model.food_respawning[i] = Math.max( timeLeft, 0 );

                if (self.model.food_respawning[i] === 0) {
                    // queue up food respawn to send to clients
                    self.model.food_respawn_ready_queue.push( i );
                }
                else {
                    self.model.food_respawning_indexes.push( i );
                }
            }
        }
    };

    /**
     * Any player checks that need to be done during serverTick, put here.
     */
    self.playersChecks = function appPlayersChecks() {
        self.model.leaders = [];

        // Iterate over all players and perform checks
        self.model.players.forEach( function performPlayerChecks(player) {
            // Spectators don't score, don't accrue infractions, and don't appear on the leaderboard
            if (player.type === Zorbio.PlayerTypes.SPECTATOR) return;

            let id = player.id;

            // Expire speed infractions
            let i = player.infractions_speed.length;
            let sum = 0;
            while (i--) {
                player.infractions_speed[i] -= config.TICK_SLOW_INTERVAL;
                if (player.infractions_speed[i] <= 0) {
                    player.infractions_speed.splice(i, 1);  // remove expired speed infraction
                }
                else {
                    sum += player.infractions_speed[i];
                }
            }

            // detect speed bursts
            let numSpeedInfractions = player.infractions_speed.length;
            if (numSpeedInfractions >= config.SPEED_BURST_DETECTION_WINDOW && !player.activeSpeedBurstDetected) {
                let mean = sum / numSpeedInfractions;
                if (mean > 7000) {
                    console.log('Speed burst detected from player id', player.id, 'mean expiry left', mean);
                    player.infractions_speed_burst++;
                    player.activeSpeedBurstDetected = true;
                }
            }
            else if (numSpeedInfractions === 0) {
                player.activeSpeedBurstDetected = false;
            }


            // Check for infractions
            if (player.infractions_food > config.INFRACTION_TOLERANCE_FOOD) {
                self.log( 'INFRACTION: Player reached food infraction tolerance:', id, player.infractions_food, config.INFRACTION_TOLERANCE_FOOD );
                player.infractions_food = 0;
            }
            else if (player.infractions_pcap > config.INFRACTION_TOLERANCE_PCAP) {
                self.log( 'INFRACTION: Player reached player capture infraction tolerance:', id, player.infractions_pcap, config.INFRACTION_TOLERANCE_PCAP );
                player.infractions_pcap = 0;
            }
            else if (player.infractions_speed.length > config.INFRACTION_TOLERANCE_SPEED ||
                player.infractions_speed_burst > config.INFRACTION_TOLERANCE_SPEED_BURST) {
                self.kickPlayer( id, 'You were removed because you had too many speed infractions.' );
            }
            else if (player.infractions_scale > config.INFRACTION_TOLERANCE_SCALE) {
                self.log( 'INFRACTION: Player reached scale infraction tolerance:', id, player.infractions_scale, config.INFRACTION_TOLERANCE_SCALE );
                player.infractions_scale = 0;
            }

            // Add players to leaders array in sorted order by score
            let score  = player.getScore();
            let leader = {
                player_id: id,
                score    : score,
            };
            UTIL.sortedObjectPush( self.model.leaders, leader, 'score' );
        } );

        // Prepare leaders array
        self.model.leaders.reverse();  // reverse for descending order
    };

    /**
     * Send any updates to client per server tick
     */
    self.sendServerTickData = function appSendServerTickData() {
        let serverTickData = {
            fr     : self.model.food_respawn_ready_queue,
            fc     : self.model.food_captured_queue,
            sm     : self.serverMsg,
            leaders: self.model.leaders,
        };

        let tickSlowMessage = { 0: Schemas.ops.TICK_SLOW, tick_data: serverTickData };
        let buffer          = Schemas.tickSlowSchema.encode( tickSlowMessage );
        self.broadcast( buffer );

        // Reset queues
        self.model.food_respawn_ready_queue = [];
        self.model.food_captured_queue      = [];
    };

    /**
     * Regularly log of server status
     * @param {number} start
     */
    function logServerStatus(start) {
        let tick_time   = perfNow() - start;
        let realPlayers = self.model.getRealPlayers();

        self.status.real_player_count = realPlayers.length;
        self.status.players_metrics   = [];
        self.status.tick_time_metric.add( tick_time );
        self.status.clients         = self.getClientCount();
        self.status.socket_uuid_map = Object.getOwnPropertyNames( self.socket_uuid_map ).length;

        for (let i = 0, l = realPlayers.length; i < l; i++) {
            self.status.players_metrics.push( realPlayers[i].getMetrics() );
        }

        // Save game status to remote data store
        // self.backend.saveGameInstanceStatus(self.uuid, self.status);

        self.log( 'Tick: ' + tick_time.toFixed( 3 ) +
            ', Clients: ' + self.status.clients +
            ', Players: ' + self.status.real_player_count +
            ', socket_uuid_map: ' + self.status.socket_uuid_map );
    }

    self.logServerStatusNth = UTIL.nth( logServerStatus,
        Math.floor( config.STATUS_LOG_DELAY / config.TICK_FAST_INTERVAL ) );

    /**
     * Main server loop for general updates to the client that should be as fast as
     * possible, eg movement and player capture.
     */
    // Admin-only: freezes bot movement and all captures/drains while the mod
    // menu is open (see handle_msg_admin_set_paused), so parameters can be
    // adjusted without anything moving or dying in the meantime. Position
    // updates and session logging keep running so connected clients don't
    // desync and training data doesn't gap.
    self.paused = false;

    self.serverTickFast = function appServerTickFast() {
        let start = perfNow();
        self.playerUpdates();
        RLState.updateVelocities( self.model );
        self.sessionLogger.logTick( self.model );

        if (!self.paused) {
            self.botController.update();
            self.updatePlayerCaptures();
            self.updateActorDrains( Drain.findAll( self.model.players ) );

            if (Date.now() - self.lastBotResetTime >= config.RL_POPULATION_RESET_INTERVAL_MS) {
                self.resetAllBots();
                self.lastBotResetTime = Date.now();
                self.log( 'Automatic periodic bot population reset (RL_POPULATION_RESET_INTERVAL_MS)' );
            }
        }

        self.sendActorUpdates();
        self.logServerStatusNth( start );
    };

    /**
     * Main server loop for general updates to the client that don't have to be
     * real-time, e.g. food respawns
     */
    self.serverTickSlow = function appServerTickSlow() {
        self.checkHeartbeats();
        self.updateFoodRespawns();
        if (!self.paused) self.checkBotFoodCaptures();
        self.playersChecks();
        self.sendServerTickData();
        Zorbio.expireLocks();
    };

    /**
     * Real players report the food they've touched over the wire
     * (msg.food_capture_queue -> self.foodCapture), but bots have no client
     * to report anything - without this, bots can never grow from food at
     * all, only from capturing other players. Runs on the slow (5Hz) tick
     * rather than the fast one since it's an O(bots * foodCount) scan and
     * food capture doesn't need to be instant.
     */
    self.checkBotFoodCaptures = function appCheckBotFoodCaptures() {
        let food = self.model.food;
        if (!food || !food.length || !self.botController.bots.length) return;

        self.botController.bots.forEach(function(bot) {
            let sphere    = bot.player.sphere;
            let pos       = sphere.position;
            let tolerance = sphere.scale + config.FOOD_CAPTURE_ASSIST + config.FOOD_CAPTURE_EXTRA_TOLERANCE;
            let toleranceSq = tolerance * tolerance;

            for (let i = 0, fi = 0; i < food.length; i += 3, fi++) {
                if (self.model.food_respawning[fi]) continue; // already eaten, respawning

                let dx = food[i]     - pos.x;
                let dy = food[i + 1] - pos.y;
                let dz = food[i + 2] - pos.z;

                if ((dx * dx + dy * dy + dz * dz) <= toleranceSq) {
                    self.foodCapture( bot.player, fi, sphere, sphere.scale );
                }
            }
        });
    };

    self.getClientCount = function appGetClientCount() {
        return Object.getOwnPropertyNames( self.clients ).length;
    };

    /**
     * Returns the count of players based on type
     * @param {string} type
     * @returns {number}
     */
    self.getPlayerCount = function appGetPlayerCount(type) {
        let player_count = 0;
        self.model.players.forEach( function eachPlayer(player) {
            if (player.type === type) {
                player_count++;
            }
        } );
        return player_count;
    };

    self.isFull = function appIsFull() {
        return self.getClientCount() >= config.MAX_PLAYERS_PER_INSTANCE;
    };

    /**
     * Admin-adjustable desired bot population (config.MAX_BOTS). Reconciles
     * the live bot count immediately - spawning or despawning - rather than
     * waiting for the next capture/disconnect to notice the new value.
     * @param {number} newMax
     */
    self.applyMaxBots = function appApplyMaxBots(newMax) {
        config.MAX_BOTS = newMax;

        while (self.botController.bots.length > newMax) {
            let bot = self.botController.popBot();
            if (!bot) break;
            // without this, already-connected clients are never told the bot
            // is gone - it just sits at its last known position forever
            // ("ghost bot"), since it stops appearing in actor updates but
            // was never explicitly removed from their scene
            self.broadcast( JSON.stringify( { op: 'remove_player', playerId: bot.player.id } ) );
        }
        while (self.botController.bots.length < newMax) {
            let bot = self.botController.spawnBot();
            if (!bot) break;
            self.broadcast( JSON.stringify( { op: 'player_join', player: bot.player } ) );
        }
    };

    /**
     * Adds a bot to the game if the population is to low
     */
    self.replenishBot = function appReplenishBot() {
        // bot was captured, lets see if we need to spawn another to replace it
        if (self.model.players.length < config.MAX_BOTS) {
            let bot = self.botController.spawnBot();
            if (!bot) return; // bots are admin-disabled

            // Notify other clients that bot has joined
            self.broadcast( JSON.stringify( { op: 'player_join', player: bot.player } ) );
        }
    };

    self.setServerMessage = function appSetServerMessage(msg) {
        self.log( 'Setting server message: ', msg );
        self.serverMsg = msg;
    };

    self.botController = new BotController( self.model );
    self.sessionLogger = new SessionLogger();

    /**
     * Clears and respawns every bot at the current world settings. Shared by
     * the admin "reset bots" button and the automatic periodic reset in
     * serverTickFast (see RL_POPULATION_RESET_INTERVAL_MS) - both just need
     * a clean population, the only difference is what triggered it.
     */
    self.resetAllBots = function appServerResetAllBots() {
        let desired = config.MAX_BOTS;

        while (self.botController.bots.length) {
            let bot = self.botController.popBot();
            self.broadcast( JSON.stringify( { op: 'remove_player', playerId: bot.player.id } ) );
        }
        for (let i = 0; i < desired; i++) {
            let bot = self.botController.spawnBot();
            if (!bot) break;
            self.broadcast( JSON.stringify( { op: 'player_join', player: bot.player } ) );
        }
    };

    self.lastBotResetTime = Date.now();

    // Start game loops
    gameloop.setGameLoop( self.serverTickFast, config.TICK_FAST_INTERVAL );
    gameloop.setGameLoop( self.serverTickSlow, config.TICK_SLOW_INTERVAL );

    // Spawn Bots
    for (let i = 0; i < config.MAX_BOTS; i++) {
        self.botController.spawnBot();
    }

    self.savePlayerScore = function appSavePlayerScore(name, score, ws) {
        ws = ws || false;

        if (score > config.INITIAL_PLAYER_SCORE) {
            self.backend.saveScore( 'zorbio', name, score, function saveScoreCallback() {
                if (self.isNewHighScore( name, score )) {
                    // Player score made it on the leaderboard so refresh and send a leaderboard update
                    self.refreshLeaderboards( function leaderSuccessCallback() {
                        if (ws && ws.readyState === WebSocket.OPEN) {
                            self.sendLeaderboardsUpdate( ws );
                        }
                    } );
                }
            } );
        }
    };

    self.isNewHighScore = function appIsNewHIghScore(name, score) {
        let allLeaderboards = [].concat( self.leaders_1_day, self.leaders_7_day, self.leaders_30_day );
        let isHighScore     = false;
        let foundIndex      = _.findIndex( allLeaderboards, ['name', name] );

        if (foundIndex >= 0) {
            // Username already has a high score, see if this one is greater
            if (score > allLeaderboards[foundIndex].score) {
                isHighScore = true;
            }
        }
        else {
            // New username see if it's greater than the smallest high score
            allLeaderboards = _.sortBy( allLeaderboards, ['score'] );

            if (score > allLeaderboards[0].score) {
                isHighScore = true;
            }
        }

        return isHighScore;
    };

    self.refreshLeaderboards = function appRefreshLeaderboards(successCallback) {
        // Get leaderboards from backend
        self.backend.getLeadersByDate( 'zorbio', config.LEADERBOARD_LENGTH, 'today', 'now', function todayLeaders(leaders, success) {
            if (leaders && leaders.length > 0) self.leaders_1_day = leaders;
            console.log( 'Retrieved 1 day leaderboard successfully?', success, self.leaders_1_day.length );

            self.backend.getLeadersByDate( 'zorbio', config.LEADERBOARD_LENGTH, '-7 days', 'now', function sevenDayLeaders(leaders, success) {
                if (leaders && leaders.length > 0) self.leaders_7_day = leaders;
                console.log( 'Retrieved 7 day leaderboard successfully?', success, self.leaders_7_day.length );

                self.backend.getLeadersByDate( 'zorbio', config.LEADERBOARD_LENGTH, '-30 days', 'now', function sevenDayLeaders(leaders, success) {
                    if (leaders && leaders.length > 0) self.leaders_30_day = leaders;
                    console.log( 'Retrieved 30 day leaderboard successfully?', success, self.leaders_30_day.length );

                    if (typeof successCallback === 'function') {
                        // success call back once all leaderboards are refreshed
                        successCallback();
                    }
                } );
            } );
        } );
    };

    // Load leaderboards on server start up
    self.refreshLeaderboards();

    // Keep leaderboards refreshed on an interval
    gameloop.setGameLoop( self.refreshLeaderboards, config.LEADERBOARD_REFRESH_INTERVAL );
};

module.exports = AppServer;
